VAR_CONFIG
	GVL.SliderLeft.pMotorBackward		AT	X32.2;
	GVL.SliderLeft.pMotorForward		AT	X32.3;
	GVL.SliderLeft.pSwitchBack		AT	X40.1;
	GVL.SliderLeft.pSwitchFront		AT	X40.0;

	GVL.SliderRight.pMotorBackward		AT	X32.4;
	GVL.SliderRight.pMotorForward		AT	X32.5;
	GVL.SliderRight.pSwitchBack		AT	X40.3;
	GVL.SliderRight.pSwitchFront		AT	X40.2;
	
	GVL.DrillingRight.pMotorBelt		AT	X33.1;
	GVL.DrillingRight.pMotorMachine		AT	X33.2;
	GVL.DrillingRight.pSensorMachine	AT	X40.7;
	
	GVL.DrillingLeft.pMotorBelt		AT	X32.7;
	GVL.DrillingLeft.pMotorMachine		AT	X33.0;
	GVL.DrillingLeft.pSensorMachine		AT	X40.5;
		
END_VAR
